### ISSUE TITLE
[Bug] Live channels are not working

### ISSUE THREAD

**Issue by riccardo1991** [phate89/plugin.video.rsich#1]
Live channels are not working. In fact `http://www.rsi.ch/play/tv/livemodule?layout=json` produces a 404.

**Comment by phate89** [comment]
I pushed a fix for live channels.. can you check if it works with this file?
https://raw.githubusercontent.com/phate89/plugin.video.rsich/master/default.py

**Comment by riccardo1991** [comment]
Yes the new version fixes it!
